### ISSUE TITLE
Choose intro emojis doesn't work

### ISSUE THREAD

**Issue by dariagrudzien** [juniorguru/juniorguru-chick#31]
While testing the bot on my own server I found out that [`choose_intro_emojis`](https://github.com/juniorguru/juniorguru-chick/blob/main/juniorguru_chick/bot.py#L82) doesn't work:

<img width="479" alt="image" src="https://github.com/juniorguru/juniorguru-chick/assets/27728733/20572e5e-b4ee-403d-bae5-b6ec271c82e7">

```
INFO:chick.bot:Processing message
INFO:chick.bot:Message sent to 'ahoj'
INFO:chick.bot:Thread 'Ahoj dariagrudzien!' created in 'ahoj'
INFO:chick.bot:Processing thread 'Ahoj dariagrudzien!' (reacting with ['👋', '🐣', '👍', '<:python:842331892091322389>', '<:database:900833211809136641>', '<:css:842343369618751519>', '<:javascript:842329110293381142>', '<:bootstrap:900834695422545940>', '<:html:842343387964375050>'] and more…)
INFO:chick.bot:Processing message
INFO:chick.bot:Message sent by the bot itself, skipping
INFO:chick.bot:Processing message
INFO:chick.bot:Message sent by the bot itself, skipping
INFO:chick.bot:Processing message
INFO:chick.bot:Message sent by the bot itself, skipping
Ignoring exception in on_thread_create
Traceback (most recent call last):
  File "/Users/dardar/Library/Caches/pypoetry/virtualenvs/juniorguru-chick-woDL3_j3-py3.11/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/Users/dardar/dev/juniorguru/juniorguru-chick/juniorguru_chick/bot.py", line 74, in on_thread_create
    await handle_intro_thread(starting_message, thread, is_bot)
  File "/Users/dardar/dev/juniorguru/juniorguru-chick/juniorguru_chick/bot.py", line 87, in handle_intro_thread
    await asyncio.gather(*tasks)
  File "/Users/dardar/Library/Caches/pypoetry/virtualenvs/juniorguru-chick-woDL3_j3-py3.11/lib/python3.11/site-packages/discord/message.py", line 1584, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/Users/dardar/Library/Caches/pypoetry/virtualenvs/juniorguru-chick-woDL3_j3-py3.11/lib/python3.11/site-packages/discord/http.py", line 371, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
```

**Comment by dariagrudzien** [comment]
Nevermind, I don't have those emojis on the server 🤦‍♀️

**Comment by honzajavorek** [comment]
Hmm, but that means it's hard to try somewhere else! I guess you won't upload all of those to your server, and even if yes, they'd have different IDs 🤔
